export { Home } from './Home'
export { AboutPage } from './About'
export { ServiciosPage } from './Servicios'
export { Portafolio } from './portafolio'
export { Faq } from './Faq' 
export { ContactoPage } from './Contacto'
export { Error404 } from './Error404'
